### ISSUE TITLE
Error  with bank overdraft after creditor and amount is entr 

### ISSUE THREAD

**Issue by stevejaubz** [LemmaLegalConsulting/docassemble-Covid19debt#100]
![Screen Shot 2022-03-26 at 10 17 28 PM](https://user-images.githubusercontent.com/66577647/160263920-8ce77900-ae5d-49c1-8869-4dd753e7c5d0.png)

[Error](https://interviews.lemmalegal.com/interview?i=docassemble.playground45BillGates%3ADebtReport.yml#)
[asouza@su.suffolk.edu](https://interviews.lemmalegal.com/interview?i=docassemble.playground45BillGates%3ADebtReport.yml#)
Error
[Retry](https://interviews.lemmalegal.com/interview?i=docassemble.playground45BillGates%3ADebtReport.yml#)

Interview has an error. There was a reference to a variable 'debt[0].emergency_dict.new_item_name' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.
History
Ran initial code at 0.00234s
id: set currency
initial: True
code: |
  set_locale(currency_symbol='£')
Tried to run mandatory code at 0.00236s
id: interview order
mandatory: True
code: |
  user_saw_introduction
  user_saw_preparation 
  debt_signpost 
  user.name.first
  user.name.last
  if user.dob.plus(years=18) > today():
    under18_kickout
  if not user.uk:
    nonUKresident_kickout
  if not user.uk_debt:
    nonUKdebt_kickout
  user.work
  user.uk_debt
  #user_provided_personal_info
  user.house_status 
  if user.house_status == 'Renting': 
    if user.renting_status == 'Joint tenants': 
      user.house_status_rentshare
  if user.house_status == 'Home owner': 
    if user.homeowner_status == 'Joint Mortgage':
      user.house_status_mortshare
  if user.house_status == 'Living with family':
    share_housing = True
  if user.house_status == 'Homeless': 
    share_housing = False
    user.house_num = 1 
    user.house_aware = False
  if share_housing == True: 
    user.house_num
  else: 
    user.house_num = 1
    user.house_aware = False
  if user.house_status == 'Homeless': 
    user_contact_information_homeless
  else:
    user_contact_information
  user.marriage

  current_insolvency
  debt_info_signpost
  
  # user_identified_priority_debts
  # user_identified_nonpriority_debts
  debt_parent_list[0]
  debt.total()
  finance_signpost
  jobs.total()
  other_income.total()
  assets.total()
  add_review_to_menu = True
  expenses.total()
  # documents_uploaded
  summary
  signpost_bs_solutions
  user_saw_standard_bs
  user_saw_mentalh_bs
  user_saw_debt_solutions
  # user_signed
  predocx_variables
  letter_and_end
Needed definition of debt[0].complete at 0.00252s
Tried to run block at 0.00269s
id: Debt complete order
generic object: Debt
code: |
  x.type
  x.value
  x.creditor
  x.name
  if temp_other_name_exists:
    x.other_name = temp_other_name
  x.urgency
  x.priority
  x.court_action
  x.first_miss_date
  x.notes
  x.complete = True
Needed definition of temp_other_name_exists at 0.00280s
Tried to run block at 0.00286s
id: tracks whether there should be other_name attribute
code: |
  temp_other_name_exists = False
Tried to run block at 0.00296s
id: Debt complete order
generic object: Debt
code: |
  x.type
  x.value
  x.creditor
  x.name
  if temp_other_name_exists:
    x.other_name = temp_other_name
  x.urgency
  x.priority
  x.court_action
  x.first_miss_date
  x.notes
  x.complete = True
Needed definition of debt[0].urgency at 0.00307s
Tried to run block at 0.00324s
id: calculates .urgency from .urgency_reason if appropriate
generic object: Debt
code: |
  if len(x.emergency_dict.true_values()) > 0:
    x.urgency = x.emergency_dict.true_values().comma_and_list()
  else:
    x.urgency = "None"
Needed definition of debt[0].emergency_dict at 0.00335s
Considered using block at 0.00350s
if: number_of_emergency_choices > 1
generic object: Debt
question: Are you at risk of any of the following relating to ${ x.name }? 
subquestion: |
  Check all that apply
  
fields:
  - no label: x.emergency_dict
    datatype: checkboxes
    code: |
      x.emergency_choices
Needed definition of number_of_emergency_choices at 0.00358s
Tried to run block at 0.00362s
generic object: Debt
code: |
  if len(x.emergency_choices) > 1:
    number_of_emergency_choices = len(x.emergency_choices)
  elif len(x.emergency_choices) == 1:
    x.initializeAttribute('emergency_dict', DADict.using(ask_number=True,target_number = 1))
    number_of_emergency_choices = len(x.emergency_choices)
  else:
    x.initializeAttribute('emergency_dict', DADict.using(auto_gather=False,gathered=True))
    number_of_emergency_choices = len(x.emergency_choices)
Needed definition of debt[0].emergency_choices at 0.00373s
Tried to run block at 0.00388s
generic object: BankOverdraft 
code: |
  x.emergency_choices = ["money being withdrawn from your account"]
Tried to run block at 0.00400s
generic object: Debt
code: |
  if len(x.emergency_choices) > 1:
    number_of_emergency_choices = len(x.emergency_choices)
  elif len(x.emergency_choices) == 1:
    x.initializeAttribute('emergency_dict', DADict.using(ask_number=True,target_number = 1))
    number_of_emergency_choices = len(x.emergency_choices)
  else:
    x.initializeAttribute('emergency_dict', DADict.using(auto_gather=False,gathered=True))
    number_of_emergency_choices = len(x.emergency_choices)
Tried to run block at 0.00418s
id: calculates .urgency from .urgency_reason if appropriate
generic object: Debt
code: |
  if len(x.emergency_dict.true_values()) > 0:
    x.urgency = x.emergency_dict.true_values().comma_and_list()
  else:
    x.urgency = "None"
Needed definition of debt[0].emergency_dict.new_item_name at 0.00433s
[Show variables and values](https://interviews.lemmalegal.com/vars?i=docassemble.playground45BillGates%3ADebtReport.yml)

**Comment by tobyfey** [comment]
Should be fixed by this commit
d04e81174b8162797300551ae25a350408cc8a5e

the reference to x.emergency_choices[0] is fine because x.emergency_dict.new_item_name will only ever be called if there is only 1 item in emergency_choices
