### ISSUE TITLE
error re: urgency 

### ISSUE THREAD

**Issue by stevejaubz** [LemmaLegalConsulting/docassemble-Covid19debt#111]
<img width="685" alt="Screen Shot 2022-03-28 at 9 40 51 PM" src="https://user-images.githubusercontent.com/66577647/160515342-65520455-7b9d-42db-975d-ba404fcfd94d.png">

[Error](https://interviews.lemmalegal.com/interview?i=docassemble.playground45mondayeve%3ADebtReport.yml#)
[asouza@su.suffolk.edu](https://interviews.lemmalegal.com/interview?i=docassemble.playground45mondayeve%3ADebtReport.yml#)
Error
[Retry](https://interviews.lemmalegal.com/interview?i=docassemble.playground45mondayeve%3ADebtReport.yml#)

Interview has an error. There was a reference to a variable 'urgency' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.
History
Ran initial code at 0.00000s
id: set currency
initial: True
code: |
  set_locale(currency_symbol='£')
Ran initial code at 0.00001s
id: enable review answers menu item
initial: True
code: |
  menu_items = [ action_menu_item('Review Answers', 'review_answers') ]
comment: |
  This block adds Review Answers to the menu immediately.  It can be switch to only add review after a certain point in the interview, when all of the information is collected.  It does this because add_review_to_menu is initially set to false (in block id: set review to false) and then changed in the interview order to True.
Tried to run mandatory code at 0.00020s
id: interview order
mandatory: True
code: |
  user_saw_introduction
  user_saw_preparation 
  debt_signpost 
  user.name.first
  user.name.last
  if user.dob.plus(years=18) > today():
    under18_kickout
  if not user.uk:
    nonUKresident_kickout
  if not user.uk_debt:
    nonUKdebt_kickout
  user.work
  user.uk_debt
  #user_provided_personal_info
  user.house_status 
  if user.house_status == 'Renting': 
    user.renting_status 
    if share_housing == True: 
      if renting_household_jt == True: 
        joint_tenancy_explained
  if user.house_status == 'Homeowner':
    mortgage_questions
    if user.homeowner_status == 'Joint Mortgage':
      user.house_status_mortshare
  if user.house_status == 'Living with family':
    share_housing = True
  if user.house_status == 'Homeless': 
    share_housing = False
    user.house_num = 1 
    user.house_aware = False
  if share_housing == True: 
    user.house_num
  else: 
    user.house_num = 1
    user.house_aware = False
  if user.house_status == 'Homeless': 
    user_contact_information_homeless
  else:
    user_contact_information
  user.marriage

  current_insolvency
  debt_info_signpost
  
  # user_identified_priority_debts
  # user_identified_nonpriority_debts
  debt_parent_list[0]
  debt.total()
  finance_signpost
  jobs.total()
  other_income.total()
  assets.total()
  add_review_to_menu = True
  expenses.total()
  # documents_uploaded
  summary
  preferencees_questions
  signpost_bs_solutions
  user_saw_standard_bs
  user_saw_mentalh_bs
  user_saw_debt_solutions
  # user_signed
  predocx_variables
  letter_and_end
Needed definition of predocx_variables at 0.00052s
Tried to run block at 0.00058s
id: collect variables before docx assembled
code: |
  total_annual_income
  total_assets
  total_expenses
  predocx_variables = True
Needed definition of total_annual_income at 0.00067s
Tried to run block at 0.00071s
id: total income calculation
code: |
  total_annual_income = currency(jobs.total() + other_income.total() + income_assets.total())
Tried to run block at 0.00091s
id: collect variables before docx assembled
code: |
  total_annual_income
  total_assets
  total_expenses
  predocx_variables = True
Needed definition of total_assets at 0.00098s
Tried to run block at 0.00102s
id: format total assets as currency
code: |
  total_assets = currency(assets.total())
Tried to run block at 0.00117s
id: collect variables before docx assembled
code: |
  total_annual_income
  total_assets
  total_expenses
  predocx_variables = True
Needed definition of total_expenses at 0.00123s
Tried to run block at 0.00127s
id: format total expenses as currency
code: |
  total_expenses = currency(expenses.total())
Tried to run block at 0.00146s
id: collect variables before docx assembled
code: |
  total_annual_income
  total_assets
  total_expenses
  predocx_variables = True
Ran initial code at 0.00152s
id: set currency
initial: True
code: |
  set_locale(currency_symbol='£')
Ran initial code at 0.00153s
id: enable review answers menu item
initial: True
code: |
  menu_items = [ action_menu_item('Review Answers', 'review_answers') ]
comment: |
  This block adds Review Answers to the menu immediately.  It can be switch to only add review after a certain point in the interview, when all of the information is collected.  It does this because add_review_to_menu is initially set to false (in block id: set review to false) and then changed in the interview order to True.
Tried to run mandatory code at 0.00167s
id: interview order
mandatory: True
code: |
  user_saw_introduction
  user_saw_preparation 
  debt_signpost 
  user.name.first
  user.name.last
  if user.dob.plus(years=18) > today():
    under18_kickout
  if not user.uk:
    nonUKresident_kickout
  if not user.uk_debt:
    nonUKdebt_kickout
  user.work
  user.uk_debt
  #user_provided_personal_info
  user.house_status 
  if user.house_status == 'Renting': 
    user.renting_status 
    if share_housing == True: 
      if renting_household_jt == True: 
        joint_tenancy_explained
  if user.house_status == 'Homeowner':
    mortgage_questions
    if user.homeowner_status == 'Joint Mortgage':
      user.house_status_mortshare
  if user.house_status == 'Living with family':
    share_housing = True
  if user.house_status == 'Homeless': 
    share_housing = False
    user.house_num = 1 
    user.house_aware = False
  if share_housing == True: 
    user.house_num
  else: 
    user.house_num = 1
    user.house_aware = False
  if user.house_status == 'Homeless': 
    user_contact_information_homeless
  else:
    user_contact_information
  user.marriage

  current_insolvency
  debt_info_signpost
  
  # user_identified_priority_debts
  # user_identified_nonpriority_debts
  debt_parent_list[0]
  debt.total()
  finance_signpost
  jobs.total()
  other_income.total()
  assets.total()
  add_review_to_menu = True
  expenses.total()
  # documents_uploaded
  summary
  preferencees_questions
  signpost_bs_solutions
  user_saw_standard_bs
  user_saw_mentalh_bs
  user_saw_debt_solutions
  # user_signed
  predocx_variables
  letter_and_end
Needed definition of letter_and_end at 0.00187s
Tried to ask question at 0.00194s
id: final document
section: conclusions
decoration: file-download
event: letter_and_end
allow downloading: True
question: |
  Below is your document with your instructions for next steps and and information about debt solutions. 
subquestion: | 
  
  Click the below image to open your document [BR]
  [BR]
  ${ pdf_concatenate([instructions_sheet, debt_brief, debt_solutions_sheet])}
  
  Click "Back" if you need to make any changes.  
  Click "Send to court" to deliver it.
attachment code: |
  [instructions_sheet, debt_brief, debt_solutions_sheet]
buttons:
  - Exit: exit
  - Restart: restart
back button: True
Needed definition of instructions_sheet at 0.00232s
Tried to run block at 0.00237s
id: instructions docx
attachment:
  - name: Next Step Instructions
    filename: Next Steps 
    variable name: instructions_sheet
    valid formats:
      - docx
      - pdf
    docx template file: debt_instructions.docx
Tried to ask question at 1.99840s
id: final document
section: conclusions
decoration: file-download
event: letter_and_end
allow downloading: True
question: |
  Below is your document with your instructions for next steps and and information about debt solutions. 
subquestion: | 
  
  Click the below image to open your document [BR]
  [BR]
  ${ pdf_concatenate([instructions_sheet, debt_brief, debt_solutions_sheet])}
  
  Click "Back" if you need to make any changes.  
  Click "Send to court" to deliver it.
attachment code: |
  [instructions_sheet, debt_brief, debt_solutions_sheet]
buttons:
  - Exit: exit
  - Restart: restart
back button: True
Needed definition of debt_brief at 1.99900s
Tried to run block at 1.99909s
id: debt brief
attachment:
  - name: Personal Debt Advisor
    filename: Debt Brief 
    variable name: debt_brief
    valid formats:
      - docx
      - pdf
    docx template file: debt_report.docx
Needed definition of emergency_debts at 2.18801s
Tried to run block at 2.18808s
id: non emergency debt code
code: |
  emergency_debts = debt.filter(urgency!="None")
Needed definition of urgency at 2.18821s
[Show variables and values](https://interviews.lemmalegal.com/vars?i=docassemble.playground45mondayeve%3ADebtReport.yml)

**Comment by tobyfey** [comment]
ec646d2
