### ISSUE TITLE
test each requirement to provide better guidance?

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-Covid19debt#16]
current logic stops testing requirements once one requirement is not me

partly addressing this comment
Yes, this is an interesting bit. It would be useful to abstract this to have greater clarity that the reasoning is correct and matches intuitions; it could be a useful support to legal advisors in clarifying relevant background information and inferences to potential solutions.

**Comment by stevejaubz** [comment]
@tobyfey is this addressing requirements for debt solutions?

**Comment by tobyfey** [comment]
.Match_dict records whether each variable is met.
