### ISSUE TITLE
Collect expenses on one screen

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-Covid19debt#21]
Use average values as defaults?

**Comment by stevejaubz** [comment]
Alternative: 
Collect expenses in groups, presenting categories: 
Housing, Childcare, Fuel, Furniture and Bedding, Health Costs, Transport, Hire purchase, Fines, Laundry/ Dry cleaning, Telephone/TV/Broadband, Other household items/toiletries and food, clothing and shoes, gifts, charitable donations and religious and cultural actvities,, other, 

https://askcpag.org.uk/?id=-216954#:~:text=END%20NOTES-,Items%20of%20expenditure,-HOUSING

**Comment by tobyfey** [comment]
This find is great - also explains why the logic also pulled out low expenses because debt advisors are supposed to ask about expenses below normal too.  But it also makes me think we need to ask about all expenses, and then determine which of the expenses can be counted as expenditures.  (Which sorta seems like the interview broke out alcohol and drugs, but the logic didn't exclude from the total.)

**Comment by stevejaubz** [comment]
How does a debt advisor look at expenses? What do they look at and want to know more? What do they have to provide additional information about? Unreasonably high? Unreasonably low?

**Comment by stevejaubz** [comment]
can we create flags for unreasonably hight? low? what does that look like and when is it important versus 

ex. if they say that they have NO income - a second screen that asks again, lists everything that can be considered incme and presents the opportunity again to add income.
