### ISSUE TITLE
In other income list, income from real estate is included, which would also be income from assets

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-Covid19debt#26]

**Comment by stevejaubz** [comment]
@tobyfey Did we resolve this? Keeping it in both might be helpful if individuals think of these things differently (i.e. someone is a landlord they think of real estate as income vs. someone who owns a home and considers it an asset)

**Comment by tobyfey** [comment]
Yes this was also fixed with cc8482656fd1a2ed4e59534f697cc4148cd6bad0
