### ISSUE TITLE
Remove 'None' and 'Back to Previous' from debt type sub categories 

### ISSUE THREAD

**Issue by stevejaubz** [LemmaLegalConsulting/docassemble-Covid19debt#46]
'None' lets you move forward without providing information or categorizing. No differnt than Other. 

Creating an "other" category where we do not sort into priority/non priority so we can capture the type . Example not captured by categories is medical debt 

Back to previous is unnecessary, if we are concerned about the Back in the upper left hand corner we should add a button at the continue level, rather than among the choices

**Comment by tobyfey** [comment]
Only difference between Other and None is that Other makes the user complete a field to write something for other.

Back to Previous and Back to Top were more useful when I tried to have the interview remember the user's last choice (thinking that somebody entering a credit card debt is likely to enter a 2nd credit card debt - of course that's different for different debt types).  But with each debt starting at the beginning it's not needed.

**Comment by tobyfey** [comment]
c5c5eab3cb4ef26b0b15e2e8fb785664dae346c8

Except I noticed that Other doesn't have the behaviour I described - it sets other_name to "Other" instead of asking the user.  Should it ask the user to complete other?

**Comment by stevejaubz** [comment]
I think naming the debt type rather than leaving it as "Other" is necessary. They may have multiple "Others" and want to make sure we capture and organize for the brief if nothing else
