### ISSUE TITLE
Use datatype: BirthDate and broader gender picker for "what is your name" screen

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#53]
![image](https://user-images.githubusercontent.com/7645641/158402956-db39fd4c-0b4e-4c8e-be0c-1a0e35ad099b.png)

It's hard to enter a birthdate with the stock date picker. 

Gender "other" is also not very inclusive--suggest using standard AL gender picker. https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/question_library/gender

**Comment by stevejaubz** [comment]
Might be silly but can we edit BirthDate datatype? The UK writes dates as DD/MM/YYY

**Comment by nonprofittechy** [comment]
Interesting point! I think the BirthDate picker has the right order of fields though--the idea is to have the alphabetic month drop down menu as the first input to help avoid mistakes. It isn't meant to be a locale-specific question.

This was part of the research we did when designing it that way, to match how Google asks it: https://ux.stackexchange.com/questions/91019/best-display-for-date-of-birth-inputs

**Comment by stevejaubz** [comment]
Great! So interesting how much consideration often goes into seemingly simple fields. I've changed made the suggested changes.
