### ISSUE TITLE
Employment situation

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#55]
![image](https://user-images.githubusercontent.com/7645641/158403809-fbd9817f-88c1-4c8d-a546-d53dceae4cc4.png)

This screen looks good--would a list of options help with "what is your occupation?"

Might also think of a more plain language phrasing for this screen. "What is your occupation"=>What kind of work do you do?

"What is your employment situation"=>"What is your work situation?" (situation isn't ideal but it is neutral as to whether employed/unemployed is better, so might be correct phrasing)

**Comment by stevejaubz** [comment]
Resolution here was to change to check boxes and allow for multiple selection but remove occupation questions. If they do have income from employment they will share the information in the income section
