### ISSUE TITLE
id: more housing questions 

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#57]
![image](https://user-images.githubusercontent.com/7645641/158406317-519d0f00-7fb6-4af0-b55c-d3580ac6ac8c.png)

Some of these feel like they should be behind a `show if`. Use radio buttons for marriage status.

"Are the people in your household aware of your debt situation" -- feels better to come closer to the solution time.

**Comment by stevejaubz** [comment]
Is it redundant to ask someone who has a joint tenancy or joint mortgage if they live with anyone else in their home? 

I am thinking, for example, someone  may have a joint mortgage with a parent that does not live with them

**Comment by stevejaubz** [comment]
Separated the family questions into more appropriate groupings
