### ISSUE TITLE
Has the creditor threatened to take immediate action against your fuel supply, property, or threatened you with imprisonment?

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#59]
![image](https://user-images.githubusercontent.com/7645641/158407152-f1ae6305-53e0-4148-8a7c-e9a95d5a06d2.png)

Very long titles can be hard to read. Suggest using a 1 or 2 line heading.

We should identify a picklist of common actions. "Creditor" should use the name of the creditor previously supplied, unless there are multiple creditors.

**Comment by stevejaubz** [comment]
Resolved by breaking apart emergency questions and only asking that which applies to each kind of debt,
