### ISSUE TITLE
id: breathing space description

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#62]
![image](https://user-images.githubusercontent.com/7645641/158413161-9a04026e-6ec7-4540-bc2e-e998a2b25d41.png)

This is easy to scan. Check UK/American English spelling (I'm not sure which is right).

The existing heading levels are not very nice, which is a Docassemble stock CSS choice. Maybe we would want to use our own CSS to format this page. Usually headings do not end with a `:`.

Avoid saying "please click here". Links should be descriptive to help with screen readers.

**Comment by stevejaubz** [comment]
Improved appearance of screens. Removed significant amount of content. Enough to share with the user that they might get a pause to catch up and encourage them to seek a debt advisor
