### ISSUE TITLE
id: mental health breathing space description 

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-Covid19debt#63]
Same comments as on #62 

![image](https://user-images.githubusercontent.com/7645641/158413747-be4fc595-6820-4c6e-81c8-85551b081eaa.png)

This is a bit longer and we might want to shorten it. Maybe phrasing each section as a question would help get someone to the right place quickly if they don't want to read everything?

**Comment by stevejaubz** [comment]
Improved content and appearance
