### ISSUE TITLE
employment situation - add more than one

### ISSUE THREAD

**Issue by stevejaubz** [LemmaLegalConsulting/docassemble-Covid19debt#67]

**Comment by tobyfey** [comment]
Do we want this here?  Why not get this information when getting/by employment information?  It seems weird to add the ability to choose multiple employment statuses when we are already collecting multiple jobs.

**Comment by tobyfey** [comment]
https://github.com/LemmaLegalConsulting/docassemble-Covid19debt/issues/55

**Comment by stevejaubz** [comment]
If we remove this question the only opportunity someone has to share a potential lack of income is in the income section which they will skip if they are unemployed. We miss information like being a student or unemployed vs retired 

It doesn't have a impact on the calculus, but might be important to a debt advisor. 

The question could be moved to seem less redundant.
